apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: application-image
    image: saksham251/application:33371c2759e9749a150b0d160824340871b66f7d
    ports:
    - containerPort: 80
# ---

# apiVersion: v1
# kind: Pod
# metadata:
#   name: httpd
# spec:
#   containers:
#   - name: httpd
#     image: httpd
#     ports:
#     - containerPort: 80
