apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: application-image
    image: saksham251/application:bbf6af349acec9111c350562b0412ca75445f34f
    ports:
    - containerPort: 80
# ---

# apiVersion: v1
# kind: Pod
# metadata:
#   name: httpd
# spec:
#   containers:
#   - name: httpd
#     image: httpd
#     ports:
#     - containerPort: 80
